---
title: "Tidyverse Train the Trainer"
author: "Day 1"
date: "1/15/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## My Goals

1. Two things I hope to get out of this workshop
    - Techniques for structuring and teaching programming to others
    - How to teach prgramming, interactively

1. A trick of the trade

## Notes

- check understanding/awareness: "What would you type into Stack Overflow to get the answer to this questions?"

- *Directed learning* 
  - flipped classroom, pre-determined path
- *Guided discovery* 
  - problem based learning, socratic method
- *Exploratory learning* 
  - teacher provides resources and promt then gets out of the way, montessori method, unschooling

- Not everyone is an auto-didact: **You Are Not Your Learners**

## Levels of Learning

6. Create
5. Evaluate
4. Analyze
3. Apply
2. Understand
1. Remember
0. Be aware of

## How to get good at anything

1. Get feedback
1. Get feedback on feedback
1. Feedback loop


- reflective practice >> 10,000 hours of practice

- Elizabeth Green: _Building A+ Better Teacher_ How teaching works

- feedback on feedback scales quickly, within ~3 rounds


## Round of teaching: critique of video

Round 1

- distracting notifications
- meaningless examples
- sitting, non dynamic, impossible to see
- hiding behind the screen
- lack of engagement with students, no feedback

Round 2

- `-` narriting during typing actions, pausing at critical moments
- `+` stopping to explain the error
- `+` stopping to explain new visual representation when it occurrs
- `-` involve students in interaction around filenames
- `+` screen looks similar to the appearance of the students' screens
- `+` explaining the use of shortcut keys (e.g. tab completion or up arrow)
- `+` Use of humor
- `+` User friendly

In the top 3 feedback items for workshops: *good to see presenters make mistakes*

## More Notes

Be a champion teacher - Lemov

Who are you when you're yourself turned up to 11

- Greg Wilson: heavy metal guitarist teacher
- vs. acoustic guitar at the coffee shop
- vs. story telling
- vs. best friend sharing new favorite band

Review examples and have class evaluate with feedback, record the feedback, then use the feedback to create a grading rubric that is later used to evaluate later examples as a group.
Can seed the group-evaluated examples with pre-wrriten examples that illustrate key conecpts.

"I'm sorry I'm going to have to ask you to shorten your question."

Get groups to work together and collaborate in the class to later continue learning after workshop/class _Wenger "Communities of practice"_

---

## Afternoon

Books

- _Small lessons_ -- when you don't have a ton of time, small bits of theory to use
- _The discussion book_ -- Getting people talking and discussing
- <http://www.learningscientists.org/> -- six methods, backed by research, to improve and enhance learning
- _The Sense of Style_ -- thoughtful writing, Steven Pinker
- _Enhancing Adult Motivation to Learn_
- _Cheating Lessons_

Motivation

Intrinsic vs. Extrinsic

- Motivators
  - Self Efficacy
  - Utility
  - Community
- Demotivators
  - Unpredictability (learned helplessness)
  - Unfairness
  - Indifference
  
Juha Sorva - Mistakes students make while programming

Anticipate learner misconceptions: search StackOverflow for common questions about the topic you'll be teaching.
