---
title: "rstudio::conf(\"notes\", day = 1)"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
```

## Keynote

### ❤️ Code

## Shiny

Cranwhales

- <cran-logs.rstudio.com>
- Shiny is good for:
  - data updated periodically
  - large computation at startup
  - possible option to drill down into lower levels
  
production is: "real users, with real consequences if things go wrong".

- keep it up
- keep it safe
- keep it correct
- keep it snappy

Organizational challenges

- IT & management tend to be skeptical
  - IT is conservative
  - Skeptical (rightly so?) of data scientists creating production software
  - Skeptical of new technology
- Engineering depts might be bias against R


Testing shiny apps for produciton

- shinyloadtest: is it slow?
- profvis: see what makes it slow
- optimize:
  - Move all the work out of Shiny and do not duplicate across users
  - Make code faster
    - Avoid text connections
    - avoid bad for loops
  - Use caching (sometimes)
  - Use async if nothing else works
- repeat

`shinyloadtest`

1. Deploy
1. Record normal session
1. Play back session concurrently using `shinyloadtest::shinycannon`
1. Go back to R and view load testing

Use `feather` for fast loading of data (blog: feather vs rds)


*Shiny in Production* - Kelly O'Briant - <http://bit.ly/shiny-prod-book>

speakerdeck.com/jcheng

---

## Shiny in production

1. commit to repo
1. jenkins to build the image
1. marathon (off-brand kubernetes)
1. mesos (deploy environment)

`plumber` doesn't support HTTPS? needed to add an APACHE layer in front of plumber to enable HTTPS. `sodium` for encryption

Enterprise web services with neuralnets using R and tensorflow

## R in production

@sellorm

the barriers to using R in organizations are cultural

two paths for getting r into organizations

- the path of "magic": a shiny app or something like that drives high-level decisions (shiny)
- the other path is technical
  - data science isn't software engineering and that's fine
  - the rigor of data science lies in code and methodological correctness
  - but software engineering has more requirements and continues much further beyond
    - CI/CD, staging servers, automated testing, security, dev ops, release management, containers, etc.
    
---

## R + ACLU

What data we collect reflects our values and our ideals

## Emily Robinson

### `funneljoin()`

- What are all the courses people started after visting the ome page for the first time?

- What percent of people saw the pricing page for the first time and then subscribed?

- What percent of people saw the pricing page and then subscribed within four days

Many funnel types - supports dplyr joins, remote tables, etc.

## Introducing MLflow for R

MLflow is an open source platform fo rthe macine learning lifecycle (databricks -- rstudio provides R interface)

- Keep track of what you did
- Replicating your results
- Bridging the gap to production

## Carpentries

How do we bring data to people? How do we bring compute to data?

Why data? "Data becomes a tool of profound social change or a weapon of political warfare -- depending on whose hands it is in" - Yeshimabeit @data4blacklives

Carpentries: software, data, library

Growth mindest using inclusive pedagogy, the 4 A:s

- Accessible
- Approachable
- Aligned
- Active

## Spatial Data Science

`sf` is for spatial geometry, `stars` for vector and raster data cubes

